<?php
/**
 * WP-CLI Commands
 *
 * @package EvolveWP PredictiveERP/CLI
 * @version 1.0.0
 */

if (!defined('ABSPATH')) {
    exit;
}

if (!class_exists('WP_CLI')) {
    return;
}

class EvolveWP_ERP_CLI_Commands {
    
    /**
     * Get plugin info
     *
     * ## EXAMPLES
     *
     *     wp evolvewp-predictiveerp info
     *
     * @when after_wp_load
     */
    public function info($args, $assoc_args) {
        WP_CLI::line('EvolveWP PredictiveERP Plugin Information:');
        WP_CLI::line('Version: ' . EVOLVEWP_ERP_VERSION);
        WP_CLI::line('Status: Active');
    }
    
    /**
     * Clear plugin cache
     *
     * ## EXAMPLES
     *
     *     wp evolvewp-predictiveerp cache clear
     *
     * @when after_wp_load
     */
    public function cache($args, $assoc_args) {
        if (isset($args[0]) && $args[0] === 'clear') {
            wp_cache_flush();
            WP_CLI::success('Cache cleared!');
        }
    }
    
    /**
     * Generate code
     *
     * ## OPTIONS
     *
     * <type>
     * : Type to generate (cpt, taxonomy, rest, settings)
     *
     * <name>
     * : Name of the item
     *
     * [--plural=<plural>]
     * : Plural name (for CPT/taxonomy)
     *
     * [--icon=<icon>]
     * : Dashicon name (for CPT)
     *
     * [--post-type=<post-type>]
     * : Post type (for taxonomy)
     *
     * [--methods=<methods>]
     * : HTTP methods (for REST, comma-separated)
     *
     * ## EXAMPLES
     *
     *     wp evolvewp-predictiveerp generate cpt Book --plural=Books --icon=book
     *     wp evolvewp-predictiveerp generate taxonomy Genre --post-type=book
     *     wp evolvewp-predictiveerp generate rest books --methods=GET,POST
     *     wp evolvewp-predictiveerp generate settings "API Settings"
     *
     * @when after_wp_load
     */
    public function generate($args, $assoc_args) {
        if (empty($args[0]) || empty($args[1])) {
            WP_CLI::error('Usage: wp evolvewp-predictiveerp generate <type> <name>');
            return;
        }
        
        $type = $args[0];
        $name = $args[1];
        
        switch ($type) {
            case 'cpt':
                $this->generate_cpt($name, $assoc_args);
                break;
            case 'taxonomy':
                $this->generate_taxonomy($name, $assoc_args);
                break;
            case 'rest':
                $this->generate_rest($name, $assoc_args);
                break;
            case 'settings':
                $this->generate_settings($name, $assoc_args);
                break;
            default:
                WP_CLI::error('Invalid type. Use: cpt, taxonomy, rest, or settings');
        }
    }
    
    private function generate_cpt($name, $args) {
        $slug = sanitize_title($name);
        $plural = isset($args['plural']) ? $args['plural'] : $name . 's';
        $icon = isset($args['icon']) ? $args['icon'] : 'admin-post';
        
        $code = "<?php
/**
 * Custom Post Type: {$name}
 * Generated by WP-CLI
 */

function evolvewp_erp_register_{$slug}_cpt() {
    register_post_type('{$slug}', array(
        'labels' => array(
            'name' => __('{$plural}', 'evolvewp-predictiveerp'),
            'singular_name' => __('{$name}', 'evolvewp-predictiveerp'),
        ),
        'public' => true,
        'has_archive' => true,
        'menu_icon' => 'dashicons-{$icon}',
        'supports' => array('title', 'editor', 'thumbnail'),
        'show_in_rest' => true,
    ));
}
add_action('init', 'evolvewp_erp_register_{$slug}_cpt');
";
        
        $file = EVOLVEWP_ERP_PLUGIN_DIR . 'includes/post-types/cpt-' . $slug . '.php';
        file_put_contents($file, $code);
        
        WP_CLI::success("Created: {$file}");
        WP_CLI::line("Add to loader.php: include_once 'includes/post-types/cpt-{$slug}.php';");
    }
    
    private function generate_taxonomy($name, $args) {
        $slug = sanitize_title($name);
        $post_type = isset($args['post-type']) ? $args['post-type'] : 'post';
        
        $code = "<?php
/**
 * Taxonomy: {$name}
 * Generated by WP-CLI
 */

function evolvewp_erp_register_{$slug}_taxonomy() {
    register_taxonomy('{$slug}', '{$post_type}', array(
        'labels' => array(
            'name' => __('{$name}', 'evolvewp-predictiveerp'),
            'singular_name' => __('{$name}', 'evolvewp-predictiveerp'),
        ),
        'public' => true,
        'hierarchical' => true,
        'show_in_rest' => true,
    ));
}
add_action('init', 'evolvewp_erp_register_{$slug}_taxonomy');
";
        
        $file = EVOLVEWP_ERP_PLUGIN_DIR . 'includes/taxonomies/taxonomy-' . $slug . '.php';
        file_put_contents($file, $code);
        
        WP_CLI::success("Created: {$file}");
        WP_CLI::line("Add to loader.php: include_once 'includes/taxonomies/taxonomy-{$slug}.php';");
    }
    
    private function generate_rest($name, $args) {
        $slug = sanitize_title($name);
        $methods = isset($args['methods']) ? explode(',', $args['methods']) : array('GET');
        $class_name = 'EvolveWP_ERP_REST_' . str_replace('-', '_', ucwords($slug, '-')) . '_Controller';
        
        $code = "<?php
/**
 * REST Controller: {$name}
 * Generated by WP-CLI
 */

class {$class_name} extends EvolveWP_ERP_REST_Controller {
    
    protected \$rest_base = '{$slug}';
    
    public function register_routes() {
        register_rest_route(\$this->namespace, '/' . \$this->rest_base, array(
            'methods' => '" . implode(',', $methods) . "',
            'callback' => array(\$this, 'get_items'),
            'permission_callback' => array(\$this, 'get_items_permissions_check'),
        ));
    }
    
    public function get_items(\$request) {
        return rest_ensure_response(array(
            'success' => true,
            'data' => array()
        ));
    }
}
";
        
        $file = EVOLVEWP_ERP_PLUGIN_DIR . 'includes/classes/rest-' . $slug . '.php';
        file_put_contents($file, $code);
        
        WP_CLI::success("Created: {$file}");
        WP_CLI::line("Add to loader.php REST API section:");
        WP_CLI::line("\$controller = new {$class_name}();");
        WP_CLI::line("\$controller->register_routes();");
    }
    
    private function generate_settings($name, $args) {
        $slug = sanitize_title($name);
        
        $code = "<?php
/**
 * Settings Page: {$name}
 * Generated by WP-CLI
 */

function evolvewp_erp_{$slug}_settings_page() {
    add_options_page(
        __('{$name}', 'evolvewp-predictiveerp'),
        __('{$name}', 'evolvewp-predictiveerp'),
        'manage_options',
        'evolvewp-predictiveerp-{$slug}',
        'evolvewp_erp_{$slug}_settings_render'
    );
}
add_action('admin_menu', 'evolvewp_erp_{$slug}_settings_page');

function evolvewp_erp_{$slug}_settings_render() {
    ?>
    <div class=\"wrap\">
        <h1><?php echo esc_html(get_admin_page_title()); ?></h1>
        <form method=\"post\" action=\"options.php\">
            <?php
            settings_fields('evolvewp_erp_{$slug}');
            do_settings_sections('evolvewp_erp_{$slug}');
            submit_button();
            ?>
        </form>
    </div>
    <?php
}
";
        
        $file = EVOLVEWP_ERP_PLUGIN_DIR . 'includes/admin/settings/settings-' . $slug . '.php';
        file_put_contents($file, $code);
        
        WP_CLI::success("Created: {$file}");
        WP_CLI::line("Add to loader.php: include_once 'includes/admin/settings/settings-{$slug}.php';");
    }
}

WP_CLI::add_command('evolvewp-predictiveerp', 'EvolveWP_ERP_CLI_Commands');
